bin: new command to add external batches for batch reporting

diff --git a/images/coog/ep b/images/coog/ep
--- a/images/coog/ep
+++ b/images/coog/ep
@@ -292,6 +292,16 @@ _batch() {
     coog_batch_exec "$@"
 }
 
+_batch_info() {
+    [ -z "$1" ] && echo "missing batch name" && return 1
+    _init || return $?
+    . "$COOG_ROOT/coog/bin/coog-redis"
+    . "$COOG_ROOT/coog/bin/coog-celery"
+    . "$COOG_ROOT/coog/bin/coog-rq"
+    . "$COOG_ROOT/coog/bin/coog-batch"
+    coog_batch_info "$@"
+}
+
 _chain() {
     [ "$#" -lt 2 ] && echo "missing arguments" && return 1
     _init || return $?
@@ -358,9 +368,11 @@ usage() {
     echo "  celery        -> starts celery workers - <workers nb> <queue,+>"
     echo "  rq            -> starts rq worker - <queue +>"
     echo "  batch         -> executes batch - <name> [args *]"
+    echo "  batch_info    -> append batch info in report "
     echo "  chain         -> executes batch chain - <module> <chain> [args *]"
     echo "  redis         -> executes redis script - <context> [args *]"
     echo "  daily         -> executes daily_chains.sh - <work days> <work days conf> <extract output>"
+    echo "  daily_mail   -> executes daily report and sends mail"
     echo "  cron          -> execute coog-cron"
     echo
 }
@@ -380,6 +392,7 @@ main() {
     [ "$cmd" = rq ] && { _rq "$@"; return $?; }
     [ "$cmd" = test ] && { _test "$@"; return $?; }
     [ "$cmd" = batch ] && { _batch "$@"; return $?; }
+    [ "$cmd" = batch_info ] && { _batch_info "$@"; return $?; }
     [ "$cmd" = chain ] && { _chain "$@"; return $?; }
     [ "$cmd" = redis ] && { _redis "$@"; return $?; }
     [ "$cmd" = daily ] && { _daily "$@"; return $?; }
