add option to mount cifs server when running coog container (#29)
Ref #7121

diff --git a/images/coog/ep b/images/coog/ep
--- a/images/coog/ep
+++ b/images/coog/ep
@@ -141,6 +141,25 @@ _uno() {
         unoconv --listener -c "pipe,name=trytond;urp;StarOffice.ComponentContext" &
 }
 
+_mount() {
+        [ -z "$MOUNT" ] && return
+        echo "########## MOUNTING ##########"
+        while IFS=';' read -ra MOUNTPOINTS; do
+            for i in "${MOUNTPOINTS[@]}"; do
+                unset OPTIONS
+                ARGS=(${i//:/ })
+                [ ! -z "${ARGS[2]}" ] && OPTIONS="-o ${ARGS[2]}"
+                mount -t cifs "${ARGS[0]}" "${ARGS[1]}" $OPTIONS
+                if [ "$?" -ne 0 ]; then
+                    echo "WARNING: failed to mount ${ARGS[0]} to ${ARGS[1]}"
+                else
+                    echo "Successfully mounted ${ARGS[0]} to ${ARGS[1]}"
+                fi
+            done
+        done <<< "$MOUNT"
+        echo "########## ######## ##########"
+}
+
 ###############
 # entrypoints #
 ###############
@@ -195,6 +214,7 @@ _server() {
         echo Welcome on board, Coog Server is preparing to start
         _init || return $?
         _uno
+        _mount
         local out
         out=/tmp/coog-docker-$HOSTNAME
         WSGI_LOG_FILE=$out uwsgi -M -T --module trytond.application:app --http :8000 --http-timeout 600 --processes "$n"
@@ -212,6 +232,7 @@ _celery() {
         echo Welcome on board, Coog Celery is preparing to start
         _init || return $?
         _uno
+        _mount
         local q
         if [ ! -z "$1" ]
         then
